# Generated by Django 5.2.6 on 2025-09-30 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctores',
            fields=[
                ('id_doctores', models.AutoField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('apellido', models.CharField(db_column='apellido', max_length=100)),
                ('numero_licencia', models.CharField(db_column='numero_licencia', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
                'db_table': 'doctores',
            },
        ),
        migrations.CreateModel(
            name='especialidades',
            fields=[
                ('id_especialidades', models.AutoField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('descripcion', models.TextField(db_column='descripcion')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'especialidades',
            },
        ),
        migrations.CreateModel(
            name='pacientes',
            fields=[
                ('id_pacientes', models.AutoField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('apellido', models.CharField(db_column='apellido', max_length=100)),
                ('fecha_nacimiento', models.DateField(db_column='fecha_nacimiento')),
                ('genero', models.CharField(db_column='genero', max_length=20)),
                ('telefono', models.CharField(db_column='telefono', max_length=20)),
                ('direccion', models.CharField(db_column='direccion', max_length=255)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'pacientes',
            },
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id_usuarios', models.AutoField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
                ('password', models.CharField(db_column='hash_contrasena', max_length=50)),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True)),
                ('rol', models.CharField(db_column='rol', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='citas',
            fields=[
                ('id_citas', models.AutoField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(db_column='fecha_hora')),
                ('motivo', models.TextField(db_column='motivo')),
                ('estado', models.CharField(db_column='estado', max_length=20)),
                ('id_doctor', models.ForeignKey(db_column='id_doctor', on_delete=django.db.models.deletion.CASCADE, to='api_app.doctores')),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, to='api_app.pacientes')),
                ('creada_por_usuario', models.ForeignKey(db_column='creada_por', on_delete=django.db.models.deletion.CASCADE, related_name='creada_por_usuario_id', to='api_app.usuarios')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'citas',
            },
        ),
        migrations.AddField(
            model_name='doctores',
            name='id_especialidad',
            field=models.ForeignKey(db_column='id_especialidad', on_delete=django.db.models.deletion.CASCADE, to='api_app.especialidades'),
        ),
        migrations.CreateModel(
            name='historial_clinico',
            fields=[
                ('id_historial_clinico', models.AutoField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('diagnostico', models.TextField(db_column='diagnostico')),
                ('tratamiento', models.TextField(db_column='tratamiento')),
                ('notas', models.TextField(blank=True, db_column='notas_doctor', null=True)),
                ('cita_id', models.ForeignKey(db_column='cita_id', on_delete=django.db.models.deletion.CASCADE, to='api_app.citas')),
            ],
            options={
                'verbose_name': 'Historial Clinico',
                'verbose_name_plural': 'Historiales Clinicos',
                'db_table': 'historial_clinico',
            },
        ),
        migrations.AddField(
            model_name='pacientes',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='api_app.usuarios'),
        ),
        migrations.AddField(
            model_name='doctores',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='api_app.usuarios'),
        ),
        migrations.CreateModel(
            name='administradores',
            fields=[
                ('id_administradores', models.AutoField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('apellido', models.CharField(db_column='apellido', max_length=100)),
                ('puesto', models.CharField(db_column='puesto', max_length=100)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='api_app.usuarios')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'administradores',
            },
        ),
    ]
